name: Deploy to Production
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      NUXT_APP_NAME: ${{ secrets.NUXT_APP_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install and Build
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "dist/*"
          target: ${{ secrets.REMOTE_DIR }}
          strip_components: 1
          rm: true
          overwrite: true
